services:
  # PostgreSQL Database for Development
  postgres:
    image: postgres:15-alpine
    container_name: saasiav3-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: saasiav3
      POSTGRES_USER: saasiav3
      POSTGRES_PASSWORD: saasiav3_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - saasiav3-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U saasiav3 -d saasiav3"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_dev_data:

networks:
  saasiav3-network:
    driver: bridge