services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: saasiav3-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: saasiav3
      POSTGRES_USER: saasiav3
      POSTGRES_PASSWORD: saasiav3_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - saasiav3-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U saasiav3 -d saasiav3"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saasiav3-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://saasiav3:saasiav3_password@postgres:5432/saasiav3
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=saasiav3-super-secret-nextauth-key-change-in-production
      - SECRET=saasiav3-super-secret-nextauth-key-change-in-production
      - NEXT_PUBLIC_SITE_URL=http://localhost:3000
      - DEFAULT_N8N_WEBHOOK=https://infra-v2-n8n-v2.uclxiv.easypanel.host/webhook/saasiav3
      - GOOGLE_CLIENT_ID=4989507711-olbqib84sdpkp1g93eu2lstli67cg9j0.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - saasiav3-network
    volumes:
      - ./public/uploads:/app/public/uploads

volumes:
  postgres_data:

networks:
  saasiav3-network:
    driver: bridge