import { Price } from "@/types/price";

export const pricingData: Price[] = [
  {
    id: "price_1NQk5TLtGdPVhGLecVfQ7mn0",
    unit_amount: 100 * 100,
    nickname: "Basic",
    offers: [
      "1 User",
      "1 Chatbot with n8n integration",
      "1GB file storage",
      "Basic downloads area",
      "All UI components",
      "Lifetime access",
      "Free updates",
      "Use on 1 (one) project",
      "3 Months support",
    ],
  },
  {
    id: "price_1NQk55LtGdPVhGLefU8AHqHr",
    unit_amount: 200 * 100,
    nickname: "Premium",
    offers: [
      "5 Users",
      "5 Chatbots with n8n integration",
      "10GB file storage",
      "Advanced downloads management",
      "Public/private file sharing",
      "All UI components",
      "Lifetime access",
      "Free updates",
      "Use on 1 (one) project",
      "3 Months support",
    ],
  },
  {
    id: "price_1NQk4eLtGdPVhGLeZsZDsCNz",
    unit_amount: 300 * 100,
    nickname: "Business",
    offers: [
      "10 Users",
      "Unlimited Chatbots",
      "100GB file storage",
      "Advanced downloads management",
      "Public/private file sharing",
      "Team collaboration features",
      "All UI components",
      "Lifetime access",
      "Free updates",
      "Use on 1 (one) project",
      "3 Months support",
    ],
  },
];
